### ISSUE TITLE
npm run dev 會報錯

### ISSUE THREAD

**Issue by kkian481718** [JiaAnTW/blog#1]
直接參考 [這篇環境設定](https://jiaantw.github.io/blog/React/basic/1_env) 裡面的步驟走，好像會報錯
![image](https://github.com/user-attachments/assets/b64ddb46-820d-4ee6-80f8-ece31a0d88e4)

可以直接修改 `./webpack.config`，加入最後一行 `mode: 'development'`
好像就可以了！

```js
module.exports = {
    
    // 以上省略
    
    devServer: {
        static: {
            directory: path.join(__dirname, './build'),
        },
        port: 8080,
    },

    mode: 'development', // 加這個才不會報錯
};
```

**Comment by kkian481718** [comment]
（謝謝您的教學，好詳細！）

**Comment by JiaAnTW** [comment]
Hi @kkian481718 , 感謝回報，已更新於 https://github.com/JiaAnTW/blog/pull/2

https://jiaantw.github.io/blog/React/basic/2_helloWorld#2-%E4%BF%AE%E6%94%B9-webpackconfigjs
